import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { authClient } from '../utils/auth';
import { authService } from '../services/authService';
import { Spinner } from '../components/shared/Spinner';

export const AuthCallbackPage: React.FC = () => {
  const navigate = useNavigate();
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const fetchSessionAndRedirect = async () => {
      try {
        // Fetch session set by Better-Auth callback cookies
        const sessionRes = await authClient.getSession();
        
        if (!sessionRes || !sessionRes.data) {
          throw new Error('No authentication session found.');
        }

        const sessionData = sessionRes.data.session as any;
        const userData = sessionRes.data.user;

        // Extract the custom stateless JWT generated by our backend hook
        const customJwt = sessionData?.authToken;

        if (!customJwt) {
          throw new Error('Stateless custom JWT token was not generated.');
        }

        // Store JWT and User data locally
        authService.setToken(customJwt);
        authService.setUser({
          id: userData.id,
          name: userData.name,
          email: userData.email,
          avatar: userData.image || undefined,
        });

        // Navigate to dashboard
        navigate('/dashboard', { replace: true });
      } catch (err: any) {
        console.error('Callback error:', err);
        setError(err.message || 'Authentication failed. Please try again.');
      }
    };

    fetchSessionAndRedirect();
  }, [navigate]);

  if (error) {
    return (
      <div className="min-h-screen bg-gray-900 flex flex-col items-center justify-center p-4 text-white">
        <div className="bg-red-500/10 border border-red-500/30 p-6 rounded-xl text-center max-w-md">
          <h2 className="text-xl font-bold text-red-400 mb-2">Authentication Failed</h2>
          <p className="text-gray-400 mb-4">{error}</p>
          <button
            onClick={() => navigate('/login')}
            className="px-4 py-2 bg-blue-600 hover:bg-blue-700 rounded-lg transition-colors"
          >
            Back to Login
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-900 flex flex-col items-center justify-center text-white">
      <Spinner className="w-12 h-12 text-blue-500 mb-4" />
      <h2 className="text-lg font-medium text-gray-300">Completing social sign-in...</h2>
      <p className="text-sm text-gray-500 mt-1">Please wait while we secure your session.</p>
    </div>
  );
};
